export const GET_ACCOUNTS_DETAIL_ADDRESS = 'GET_ACCOUNTS_DETAIL_ADDRESS';
export const GET_ACCOUNTS_DETAIL_ADDRESS_LOADING =
  'GET_ACCOUNTS_DETAIL_ADDRESS_LOADING';

export const GET_TRANSACTIONS_BY_ADDRESSES = '  GET_TRANSACTIONS_BY_ADDRESSES';
export const GET_TRANSACTIONS_BY_ADDRESSES_LOADING =
  '  GET_TRANSACTIONS_BY_ADDRESSES_LOADING';
