export const GET_ACCOUNT_DETAILS = 'GET_ACCOUNT_DETAILS';
export const GET_ACCOUNT_DETAILS_LOADING = 'GET_ACCOUNT_DETAILS_LOADING';

export const GET_TRANSACTIONS_BY_ADDRESS = '  GET_TRANSACTIONS_BY_ADDRESS';
export const GET_TRANSACTIONS_BY_ADDRESS_LOADING =
  '  GET_TRANSACTIONS_BY_ADDRESS_LOADING';

export const GET_RECIEVED_TXS_BY_ADDRESS = '  GET_RECIEVED_TXS_BY_ADDRESS';
export const GET_RECIEVED_TXS_BY_ADDRESS_LOADING =
  '  GET_RECIEVED_TXS_BY_ADDRESS_LOADING';

export const GET_SENT_TXS_BY_ADDRESS = '  GET_SENT_TXS_BY_ADDRESS';
export const GET_SENT_TXS_BY_ADDRESS_LOADING =
  '  GET_SENT_TXS_BY_ADDRESS_LOADING';
