export const GET_ALL_BLOCKS = 'GET_ALL_BLOCKS';
export const GET_ALL_BLOCKS_LOADING = 'GET_ALL_BLOCKS_LOADING';

export const GET_BLOCKS_BY_HEIGHT = 'GET_BLOCKS_BY_HEIGHT';
export const GET_BLOCKS_BY_HEIGHT_LOADING = 'GET_BLOCKS_BY_HEIGHT_LOADING';
