export const GET_MARKET_PRICE = 'GET_MARKET_PRICE';
export const GET_MARKET_PRICE_LOADING = 'GET_MARKET_PRICE_LOADING';
export const GET_COIN_PRICE = 'GET_COIN_PRICE';
export const GET_COIN_PRICE_LOADING = 'GET_COIN_PRICE_LOADING';
