export const GET_MARKET_PRICE = 'GET_MARKET_PRICE';
export const GET_MARKET_PRICE_LOADING = 'GET_MARKET_PRICE_LOADING';
export const GET_PRICE = 'GET_PRICE';
export const GET_PRICE_LOADING = 'GET_PRICE_LOADING';
