export const GET_TOTAL_SUPPLY = 'GET_TOTAL_SUPPLY';
export const GET_TOTAL_SUPPLY_LOADING = 'GET_TOTAL_SUPPLY_LOADING';
export const GET_PRICE = 'GET_PRICE';
export const GET_PRICE_LOADING = 'GET_PRICE_LOADING';
export const GET_NODE_INFO = 'GET_NODE_INFO';
export const GET_NODE_INFO_LOADING = 'GET_NODE_INFO_LOADING';
export const GET_LATEST_BLOCKS = 'GET_LATEST_BLOCKS';
export const GET_LATEST_BLOCKS_LOADING = 'GET_LATEST_BLOCKS_LOADING';
export const GET_LATEST_TRANSACTIONS = 'GET_LATEST_TRANSACTIONS';
export const GET_LATEST_TRANSACTIONS_LOADING =
  'GET_LATEST_TRANSACTIONS_LOADING';
