export const GET_All_TRANSACTIONS = 'GET_All_TRANSACTIONS';
export const GET_All_TRANSACTIONS_LOADING = 'GET_All_TRANSACTIONS_LOADING';

export const GET_TRANSACTIONS_BY_HASH = 'GET_TRANSACTIONS_BY_HASH';
export const GET_TRANSACTIONS_BY_HASH_LOADING =
  'GET_TRANSACTIONS_BY_HASH_LOADING';
